// Code generated by "stringer -type PartitionType -linecomment -output stringers.go"; DO NOT EDIT.

package mbr

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[PartitionTypeUnused-0]
	_ = x[PartitionTypeFAT12-1]
	_ = x[PartitionTypeFAT16Small-4]
	_ = x[PartitionTypeExtended-5]
	_ = x[PartitionTypeFAT16-6]
	_ = x[PartitionTypeNTFS-7]
	_ = x[PartitionTypeFAT32CHS-11]
	_ = x[PartitionTypeFAT32LBA-12]
	_ = x[PartitionTypeFAT16LBA-14]
	_ = x[PartitionTypeExtendedLBA-15]
	_ = x[PartitionTypeWindowsRE-39]
	_ = x[PartitionTypeLinuxSwap-130]
	_ = x[PartitionTypeLinux-131]
	_ = x[PartitionTypeLinuxExtended-133]
	_ = x[PartitionTypeLinuxLVM-142]
	_ = x[PartitionTypeFreeBSD-165]
	_ = x[PartitionTypeOpenBSD-166]
	_ = x[PartitionTypeNetBSD-169]
	_ = x[PartitionTypeAppleBoot-171]
	_ = x[PartitionTypeAppleHFS-175]
	_ = x[PartitionTypeSolaris-191]
	_ = x[PartitionTypeGPTProtective-238]
	_ = x[PartitionTypeEFISystem-239]
	_ = x[PartitionTypeLinuxRAID-253]
}

const _PartitionType_name = "unusedfat12fat16 <32MBextendedfat16ntfs/exfatfat32-chsfat32-lbafat16-lbaextended-lbawindows-recoverylinux-swaplinuxlinux-extendedlinux-lvmfreebsdopenbsdnetbsdapple-bootapple-hfssolarisgpt-protectiveefi-systemlinux-raid"

var _PartitionType_map = map[PartitionType]string{
	0:   _PartitionType_name[0:6],
	1:   _PartitionType_name[6:11],
	4:   _PartitionType_name[11:22],
	5:   _PartitionType_name[22:30],
	6:   _PartitionType_name[30:35],
	7:   _PartitionType_name[35:45],
	11:  _PartitionType_name[45:54],
	12:  _PartitionType_name[54:63],
	14:  _PartitionType_name[63:72],
	15:  _PartitionType_name[72:84],
	39:  _PartitionType_name[84:100],
	130: _PartitionType_name[100:110],
	131: _PartitionType_name[110:115],
	133: _PartitionType_name[115:129],
	142: _PartitionType_name[129:138],
	165: _PartitionType_name[138:145],
	166: _PartitionType_name[145:152],
	169: _PartitionType_name[152:158],
	171: _PartitionType_name[158:168],
	175: _PartitionType_name[168:177],
	191: _PartitionType_name[177:184],
	238: _PartitionType_name[184:198],
	239: _PartitionType_name[198:208],
	253: _PartitionType_name[208:218],
}

func (i PartitionType) String() string {
	if str, ok := _PartitionType_map[i]; ok {
		return str
	}
	return "PartitionType(" + strconv.FormatInt(int64(i), 10) + ")"
}
